Combined AcceptApplication, RejectApplication, and GetApplication
sherwinokhowat/Group-Formation-System pull request #114
Opened 2024-08-01 23:13 UTC by tArthur1

Combined AcceptApplication, RejectApplication, and GetApplication into ManageApplications use_case

2024-08-01 23:20 UTC, sherwinokhowat requested changes
Please do it for projects and users as well. That is, combine them into manageprojects and manageusers usecases.

2024-08-02 00:05 UTC, Raqkkkkk commented
Also we might need to update tests after this.

2024-08-03 01:52 UTC, tArthur1 commented
Please review my pull request, I've combined use cases for project and users into ManageProjects and ManageUsers respectively.

2024-08-03 06:08 UTC, Raqkkkkk requested changes
overall seems to only have some minor formatting and style issues
functionality should be fine if the tests still pass

2024-08-03 06:08 UTC, Raqkkkkk commented on src/main/java/Main.java
> +        ManageUsersController manageUsersUseCaseFactory = ManageUsersUseCaseFactory.create(createUserPanelViewModel, editProfileViewModel);
I think this variable could be changed to another name to make it more clear what it is (like manageUsersController).

2024-08-03 06:08 UTC, Raqkkkkk commented on src/main/java/usecase/manageusers/ManageUsersController.java
remember to delete commented out code if it is no longer needed

2024-08-03 11:54 UTC, sherwinokhowat requested changes
Please move the associated packages to the combined use case package. For example, the create application package should be nested inside of the manageapplications package. This applies to the rest of the combined usecases as well.

2024-08-05 17:50 UTC, tArthur1 commented
I moved each use case into their respective manage use case, please review my request.

2024-08-05 18:23 UTC, merged

2024-08-05 20:52 UTC, Raqkkkkk commented
Dealt with requested changes during merge