Implementation of GetUsers view, viewmodel and testing
sherwinokhowat/Group-Formation-System pull request #133
Opened 2024-08-06 22:54 UTC by Pixeldom4

1. **Addition of UsersPanel Class:**
Created a new UsersPanel class to display user information in a tabular format.
The panel is initialized with columns for user details like First Name, Last Name, Email, Tags, Desired Compensation, and Is Owner.

2. **Integration of UsersPanel into MyProjectsPanel:**
Added a JButton to MyProjectsPanel to fetch and display user information.
Included a UsersPanel instance in MyProjectsPanel.
Updated the actionPerformed method to handle the button click event, fetch user data, and display it in a new frame containing the UsersPanel.

3. **Enhancements to MyProjectsPanelViewModel:**
Added methods to handle user data (setUsersData) and to store and retrieve the selected project ID.

4. **Adjustments to the MyProjectsPanel Layout and Behavior:**
Modified the addProjects method to include a hidden project ID column, essential for internal logic but not visible to users.
Updated property change handling to manage new user data updates and project selections.

5. **New Unit Tests for MyProjectsPanel:**
Added tests to verify the new functionality, including handling user data updates, displaying user information, and managing project data.

2024-08-06 22:57 UTC, Pixeldom4 commented
I've made adjustments based on Rawq's [suggestions](https://github.com/sherwinokhowat/Group-Formation-System/pull/132#issue-2449765299). Thank you for the feedback!

2024-08-07 00:31 UTC, Raqkkkkk requested changes
I think that the get users button can be put into the table and have one for each project rather than having it on the bottom

2024-08-07 00:31 UTC, Raqkkkkk commented on src/test/java/view/MyProjectsPanelTest.java
> +//    }
remove commented code

2024-08-07 00:31 UTC, Raqkkkkk commented on src/main/java/view/MyProjectsPanel.java
> +            usersFrame.setSize(800, 600);
can set to a smaller size

2024-08-07 01:00 UTC, sherwinokhowat requested changes
Everything looks good, but it would be nice if you delete the commented out code if it is not used.

2024-08-07 01:08 UTC, Raqkkkkk approved these changes
new commits look nice :D

2024-08-07 01:08 UTC, sherwinokhowat approved these changes
W changes :D

2024-08-07 01:13 UTC, merged